cask_args appdir: "/Applications"

tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"

# System Applications
brew "gitmoji"
brew "starship"

# Paid Applications
cask "1password"
cask "affinity-designer"
cask "affinity-photo"
cask "affinity-publisher"
cask "backblaze"
cask "bartender"
cask "cleanmymac"
cask "cleanshot"

# Free Applications
cask "authy"
cask "bitwarden"
cask "discord"
cask "figma"
cask "firefox"
cask "github"
cask "google-chrome"
cask "imageoptim"
cask "notion"
cask "obs"
cask "obsidian"
cask "raycast"
cask "sf-symbols"
cask "signal"
cask "slack"
cask "syncthing"
cask "twitch"
cask "visual-studio-code"
