cask_args appdir: "/Applications"

tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"

# System Applications
brew "gitmoji"
brew "starship"
brew "gnupg"

# Paid Applications
cask "1password"
cask "cleanshot"

# Free Applications
cask "figma"
cask "firefox"
cask "github"
cask "google-chrome"
cask "imageoptim"
cask "obsidian"
cask "sf-symbols"
cask "slack"
cask "visual-studio-code"
