cask_args appdir: "/Applications"

tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"

brew "gitmoji"
brew "starship"

# Paid Applications
cask "1password"
cask "backblaze"
cask "bartender"
cask "one-switch"
cask "sizzy"
cask "sublime-merge"
cask "sublime-text"

# Free Applications
cask "alfred"
cask "amethyst"
cask "authy"
cask "bitwarden"
cask "figma"
cask "firefox"
cask "github"
cask "google-chrome"
cask "grammarly"
cask "hyper" 
cask "obs"
cask "obsidian"
cask "visual-studio-code"
